apiVersion: v1
kind: Template
labels:
  template: test-configmap-template
message: "Deploying using templated resources"
metadata:
  name:  configmap-template
objects:
- apiVersion: v1
  kind: ConfigMap
  data:
    cgroup: ${CGROUP}
    topicname: ${TOPIC_NAME}
  metadata:
    name: ${APP_NAME}-config-map
############################################
parameters:
- description: The name for the microservice
  displayName: Microservice Name
  name: APP_NAME
  required: true

- description: A consumer group name
  displayName: consumer group name
  name: CGROUP
  required: true

- description: A topic name
  displayName: topic name
  name: TOPIC_NAME
  required: true
