apiVersion: v1
kind: Template
labels:
  template: cronjob-template
message: Deploying using templated resources
metadata:
  name: cronjob-template
objects:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: ${APP_NAME}
  spec:
    concurrencyPolicy: Allow
    failedJobsHistoryLimit: 3
    jobTemplate:
      metadata:
      spec:
        template:
          metadata:
          spec:
            containers:
            - command:
              - ${INTERPRETER}
              - ${EXECUTABLE}
              image: ${IMAGE_REPOSITORY}/${PROJECT_ID}-${MICROSERVICE_NAME}:${IMAGE_TAG}
              imagePullPolicy: Always
              name: ${APP_NAME}
              resources:
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEM_LIMIT}
                requests:
                  cpu: ${CPU_REQ}
                  memory: ${MEM_REQ}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            imagePullSecrets:
              - name: ${PULL_SECRET}
            restartPolicy: OnFailure
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
    schedule: ${SCHEDULE}
    successfulJobsHistoryLimit: 3
    suspend: false
############################################
parameters:
- description: The cluster wildcard domain
  displayName: Cluster Wildcard Domain
  name: CLUSTER_WILDCARD_DOMAIN
  required: true

- description: The image repository where the image to be deployed exists
  displayName: Image Repository
  name: IMAGE_REPOSITORY
  required: true

- description: The image repository where the image to be deployed exists
  displayName: Image Repository
  name: PULL_SECRET
  required: true

- description: The name for the microservice
  displayName: Microservice Name
  name: MICROSERVICE_NAME
  required: true

- description: The name for the application
  displayName: Application Name
  name: APP_NAME
  required: true

- description: The Project ID
  displayName: Project ID
  name: PROJECT_ID
  required: true

- description: The name of the environment
  displayName: Environment Name
  name: ENV
  required: true

- description: The name of the image tag
  displayName: Image Tag
  name: IMAGE_TAG
  required: true
  value: latest

- description: Interpreter program to run
  displayName: Interpreter program
  name: INTERPRETER
  required: true

- description: Full path to executable program
  displayName: executable program
  name: EXECUTABLE
  required: true

- description: cronjob schedule
  displayName: cronjob schedule
  name: SCHEDULE
  required: true

- description: CPU Resource Request (Floor) in millicores
  displayName: CPU Resource Request in millicores
  name: CPU_REQ
  required: true
  value: 100m

- description: CPU Resource Limit (Ceiling) in millicores
  displayName: CPU Resource Limit in millicores
  name: CPU_LIMIT
  required: true
  value: 200m

- description: Memory Resource Request (Floor) in Mi or Gi
  displayName: Memory Resource Request in Mi or Gi
  name: MEM_REQ
  required: true
  value: 50Mi

- description: Memory Resource Limit (Ceiling) in Mi or Gi
  displayName: Memory Resource Limit in Mi or Gi
  name: MEM_LIMIT
  required: true
  value: 500Mi
