elCicdDefs:
  CGROUP: cgroup
  TOPIC_NAME: topicname
  VOLUME_NAME: cm-mount
  CONFIG_MAP: config-map
  PASSWORD: password

elCicdTemplates:
- templateName: cronjob
  schedule: "*/3 * * * *"
  env: 
  - name: PYTHONUNBUFFERED
    value: "1"
  - name: $<PASSWORD>
    valueFrom:
      secretKeyRef:
        key: $<PASSWORD>
        name: $<COMPONENT_NAME>-sealed-secret
  - name: $<CGROUP>
    valueFrom:
      configMapKeyRef:
        key: $<CGROUP>
        name: $<COMPONENT_NAME>-$<CONFIG_MAP>
  - name: $<TOPIC_NAME>
    valueFrom:
      configMapKeyRef:
        key: $<TOPIC_NAME>
        name: $<COMPONENT_NAME>-$<CONFIG_MAP>
  volumeMounts:
  - name: $<VOLUME_NAME>
    mountPath: /mnt
  volumes:
  - name: $<VOLUME_NAME>
    configMap:
      name: $<COMPONENT_NAME>-$<CONFIG_MAP>

- templateName: configMap
  objName: $<COMPONENT_NAME>-$<CONFIG_MAP>
  data:
    $<CGROUP>: $<SDLC_ENV>$<CGROUP>
    $<TOPIC_NAME>: $<SDLC_ENV>topic
